### ISSUE TITLE
Explain side-effects of using tinkr

### ISSUE THREAD

**Issue by maelle** [maelle/aeolus#5]
- Loss of formatting
- Known tinkr issues

**Comment by yabellini** [comment]
I don't know if it is related, but when I used it with the index of the Champions program, the YAML broke.

**Comment by maelle** [comment]
In some of the content files of roweb3, metadata is in TOML not YAML and TOML isn't supported by tinkr indeed :melting_face:

**Comment by yabellini** [comment]
Ohh, yes it is TOML because it use +++ instead of ---

**Comment by maelle** [comment]
https://github.com/ropensci/tinkr/issues/126
